export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const SET_ALL_CATEGORIES = "SET_ALL_CATEGORIES";
export const ADD_PRODUCT_TO_ORDER = "ADD_PRODUCT_TO_ORDER";
export const CHANGE_PRODUCT_COUNT = "CHANGE_PRODUCT_COUNT";
export const REMOVE_PRODUCT_FROM_ORDER = "REMOVE_PRODUCT_FROM_ORDER";